<a href="https://colab.research.google.com/github/Ramsaini786/Aws-python/blob/main/Day7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#File Handling

1.   "r"--> Read
2.   "w'--> write
3.   "a" --> Append


In [1]:
#read
from google.colab import drive
#drive.mount('/content/drive')
data = open('/content/drive/MyDrive/nikhil.txt', 'r')
data.read()

'Good Morning  Nikhil  Saini'

In [2]:
#read
from google.colab import drive
#drive.mount('/content/drive')
data = open('/content/drive/MyDrive/file1.csv', 'r')
data.read()

'12345678'

In [3]:
data = open('/content/drive/MyDrive/nikhil.txt', 'w')
data.write("nikhil jjjjjjjjj")

16

In [4]:
data = open('/content/drive/MyDrive/nikhil.txt', 'r')
data.read()

'nikhil jjjjjjjjj'

In [5]:
#Write and Read
data = open('/content/drive/MyDrive/nikhil.txt', 'w')
data.write("Ram Ram bhaiyo")
data = open('/content/drive/MyDrive/nikhil.txt', 'r')
data.read()

'Ram Ram bhaiyo'

In [6]:
data = open('/content/drive/MyDrive/nikhil.txt', 'r')
data.read()
data= open('/content/drive/MyDrive/nikhil.txt', 'w')
data.write("Good Morning")

data = open('/content/drive/MyDrive/nikhil.txt', 'a')
data.write("  Nikhil  Saini")



15

In [7]:
data = open('/content/drive/MyDrive/nikhil.txt', 'r')
data.read()

'Good Morning  Nikhil  Saini'

In [8]:
from google.colab import drive
#drive.mount('/content/drive')
data = open('/content/drive/MyDrive/file1.csv', 'r')
data.read()


'12345678'

In [9]:
data = open('/content/drive/MyDrive/file1.csv', 'r')
data.read()
data = open('/content/drive/MyDrive/file1.csv', 'w')
data.write('1234')

4

In [10]:
data = open('/content/drive/MyDrive/file1.csv', 'r')
data.read()

'1234'

In [11]:
data = open('/content/drive/MyDrive/file1.csv', 'r')
data.read()
data = open('/content/drive/MyDrive/file1.csv', 'w')
data.write('1234')
data = open('/content/drive/MyDrive/file1.csv','a')
data.write('5678')

4

In [12]:
data = open('/content/drive/MyDrive/file1.csv', 'r')
data.read()

'12345678'

In [15]:
#direct access without drive
data = open('nikhil.txt', 'r')
data.read()

FileNotFoundError: [Errno 2] No such file or directory: 'nikhil.txt'

In [ ]:
#direct access csv file
data= open('file1.csv', 'r')
data.read()

In [ ]:
data = open('nikhil.txt', 'r')
data.read()
data = open('nikhil.txt', 'w')
data.write("Good Morning")

data = open('nikhil.txt', 'a')
data.write("  Nikhil  Saini")


In [ ]:
data = open('nikhil.txt', 'r')
data.read()

In [ ]:
data= open('file1.csv', 'r')
data.read()
data = open('file1.csv', 'w')
data.write('1234')
data = open('file1.csv','a')
data.write('5678')

In [ ]:
data= open('file1.csv', 'r')
data.read()

#Numpy or pandas

In [17]:
import numpy as np

In [18]:
#1d
l= [10,20,30,40]
l*2
#power of numpy
arr=np.array(l)
arr*2

array([20, 40, 60, 80])

In [19]:
import numpy as np

In [20]:
arr=np.array([1,2,3,4,5])
print(arr[0])
print(arr[1])

1
2


In [21]:
import numpy as np
l=[10,20,30,40]
print(l)
print(type(l))
arr=np.array(l)
print(arr)
print(type(arr))

[10, 20, 30, 40]
<class 'list'>
[10 20 30 40]
<class 'numpy.ndarray'>


In [22]:
#Change Value
import numpy as np
l=[10,20,30,40]
l[0]=100
l[1]=200
print(l)
#numpy
arr=np.array(l)
arr[0]=100
arr[1]=200
print(arr)


[100, 200, 30, 40]
[100 200  30  40]


In [23]:
import numpy as np
l=[10,20,30,40]
#print(l+2) #add not acceptable with list

arr = np.array(l)
print(arr+2) #add acceptable with numpy

[12 22 32 42]


In [24]:
#arange in numpy
import numpy as np
arr=np.arange(10,20,2)
print(arr)

[10 12 14 16 18]


In [25]:
arr=np.arange(1,5)#start,stop,jump
print(arr)
arr=np.arange(1,7,2)
print(arr)

[1 2 3 4]
[1 3 5]


In [26]:
for i in range(1,5):
  print(i)


1
2
3
4


In [27]:
# simple Example
import numpy as np
l=[[1,2,3],[4,5,6]]
print(l)
print(l[0][1])
print("numpy start")
arr=np.array(l)
print(arr)
print(arr[0][1])

[[1, 2, 3], [4, 5, 6]]
2
numpy start
[[1 2 3]
 [4 5 6]]
2


In [34]:
import numpy as np
l=[[1,2,3,4],[5,7,8,9],[4,2,1,0]]
print(l)
print(l[0][2])
#numpy
arr=np.array(l)
print(arr)
print(arr[0][2])

[[1, 2, 3, 4], [5, 7, 8, 9], [4, 2, 1, 0]]
3
[[1 2 3 4]
 [5 7 8 9]
 [4 2 1 0]]
3


In [42]:
#1d vertix
#2d matrix
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [44]:
#2d
import numpy as np

arr = np.arange(1, 13).reshape(3, 4)

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [38]:
import numpy as np

# 2D Array (Rows and Columns)
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr2d)


[[1 2 3]
 [4 5 6]]


In [46]:
#2d Adition
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(a + b)

[[ 6  8]
 [10 12]]


In [41]:
#3d tensor
import numpy as np

# 3D Array
arr3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print(arr3d)
print(arr2d[0][2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [48]:
#Access Elements in 3D Array
import numpy as np

arr = np.array([
    [[10, 20], [30, 40]],
    [[50, 60], [70, 80]]
])
print(arr)
print(arr[1, 0, 1])

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]
60


In [49]:
import numpy as np

arr = np.arange(1, 25).reshape(2, 3, 4)

print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [53]:
import numpy as np

sales = np.array([
    [[100, 120, 140],
     [150, 160, 170]],

    [[200, 220, 240],
     [250, 260, 270]]
])
print(sales)
print(arr[1, 1, 1])

[[[100 120 140]
  [150 160 170]]

 [[200 220 240]
  [250 260 270]]]
18
