<a href="https://colab.research.google.com/github/Ramsaini786/Aws-python/blob/main/Day8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#numpy | List
import numpy as np
import time
#for list
start=time.time()
sum1 = 0
for i in range(1000000):
  sum1 += i*2
end=time.time()
print("for list",sum1,end-start)
# for numpy| array(array work every element|wise)
start1 = time.time()
sum2 = 0
arr = np.arange(1000000)*2
sum2 = arr.sum()
end1 = time.time()
print("for numpy",sum2,end1-start1)



for list 999999000000 0.09534835815429688
for numpy 999999000000 0.0017824172973632812


In [ ]:
import numpy as np
import time

start = time.time()
sum1 = 0
for i in range(1000000):
  sum1 += i*2
end =time.time()
print("for list",sum1,end-start)

start1 = time.time()
sum2 = 0
arr = np.array(1000000)*2
sum2 = arr.sum()
end1 = time.time()
print("for numpy",sum2,end1-start1)

for list 999999000000 0.096282958984375
for numpy 2000000 0.00026535987854003906


In [ ]:
#zeros
import numpy as np
#array 1d
arr = np.zeros(5)
print(arr)
#2d
arr1 = np.zeros((2,3))#2 row and 3 col
print(arr1)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#ones
import numpy as np
#1d array
arr=np.ones(4)
print(arr)
#2d array
arr1=np.ones((5,7))
print(arr1)

[1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
#full
#1d
import numpy as np
arr = np.full((4),5)
#2d
print(arr)
arr1 = np.full((4,3),2)
print(arr1)

[5 5 5 5]
[[2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]]


In [ ]:
#zeros addition another number
import numpy as np
#array 1d
arr = np.zeros(5)+2
print(arr)
#2d
arr1 = np.zeros((2,3))+3#2 row and 3 col
print(arr1)

[2. 2. 2. 2. 2.]
[[3. 3. 3.]
 [3. 3. 3.]]


In [ ]:
#Shape
import numpy as np
arr = np.zeros(5)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
#2d
arr1 = np.zeros((2,3))
print(arr1)
print(arr1.shape)
print(arr1.ndim)
print(arr1.size)
print(arr1.dtype)


[0. 0. 0. 0. 0.]
(5,)
1
5
float64
[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)
2
6
float64


In [ ]:
#ones
import numpy as np
#1d array
arr=np.ones(4)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
#2d array
arr1=np.ones((5,7))
print(arr1)
print(arr1.shape)
print(arr1.ndim)
print(arr1.size)
print(arr1.dtype)


[1. 1. 1. 1.]
(4,)
1
4
float64
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
(5, 7)
2
35
float64


In [ ]:
#full
import numpy as np
arr = np.full((3),4)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
#2d array
arr1 = np.full((4,3),2)
print(arr1)
print(arr1.shape)
print(arr1.ndim)
print(arr1.size)
print(arr1.dtype)

[4 4 4]
(3,)
1
3
int64
[[2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]]
(4, 3)
2
12
int64


In [ ]:
#reshape
#1d array
import numpy as np
arr = np.arange(5)
print(arr)
arr1=arr.reshape(5,1)
print(arr1)

[0 1 2 3 4]
[[0]
 [1]
 [2]
 [3]
 [4]]


In [ ]:
arr1=np.arange((3,2)) # reason reshape use
print(arr1)

In [ ]:
#flatten
import numpy as np
arr = np.arange(6)
arr1=arr.reshape(2,3)
print(arr1)
#flatten
print(arr1.flatten())

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]


In [ ]:
#Ravel
import numpy as np
arr = np.arange(6).reshape(2,3)
print(arr)
#ravel
print(arr.ravel())


[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]


In [ ]:
import numpy as np
arr = np.arange(6).reshape(2,3).ravel()
print(arr)

[0 1 2 3 4 5]


In [ ]:
#flatten || copy//Return copy of the original array
import numpy as np
arr = np.arange(6)
arr1=arr.reshape(2,3)
print(arr1)
#flatten
arr_new=arr1.flatten()
arr_new[0]=100
print(arr1)


[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]


In [ ]:
#Ravel//Return only reference/view of the original array
import numpy as np
arr = np.arange(6).reshape(2,3)
print(arr)
#ravel
arr_new = arr.ravel()
arr_new[0]=200
print(arr)

[[0 1 2]
 [3 4 5]]
[[200   1   2]
 [  3   4   5]]


In [ ]:
#Transpose
import numpy as np
arr = np.arange(6).reshape(2,3)
print(arr)
#transpose
print(arr.transpose())

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


In [ ]:
#Transpose
import numpy as np
arr = np.arange(6).reshape(2,3)
print(arr)
#transpose
arr1 = arr.T
print(arr1)


[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


In [ ]:
#Transpose
import numpy as np
arr = np.arange(6).reshape(2,3).transpose()
print(arr)

[[0 3]
 [1 4]
 [2 5]]


In [5]:
#3d array zeros
import numpy as np
arr = np.zeros((2,3,4))
print(arr)


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [7]:
import numpy as np
arr = np.zeros((2,3,4))
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
(2, 3, 4)
3
24
float64


In [8]:
#3d array ones
import numpy as np
arr = np.ones((2,3,4))
print(arr)


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [10]:
import numpy as np
arr = np.ones((2,3,4))
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
(2, 3, 4)
3
24
float64


In [12]:
#3d array full
import numpy as np
arr = np.full((2,3,4),5)
print(arr)


[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]]


In [13]:
import numpy as np
arr = np.full((2,3,4),5)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]]
(2, 3, 4)
3
24
int64
