<a href="https://colab.research.google.com/github/Ramsaini786/Aws-python/blob/main/Day9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr = np.array([10,20,3,4,90,200])
arr_f = arr[arr>20]
print(arr_f)

[ 90 200]


In [3]:
import numpy as np
arr = np.array([10,20,3,0,6,3,2])
arr_f = arr[arr!=6]
print(arr_f)

[10 20  3  0  3  2]


In [8]:
#example and opr 10 se 20 btween
import numpy as np
arr = np.array([10,20,3,0,6,3,2,50,40,110])
arr_f =arr[(arr > 10) & (arr < 20) ]
print(arr_f)

[]


In [9]:
arr = np.array([5,12,15,18,20,25])

arr_f = arr[(arr > 10) & (arr < 20)]

print(arr_f)

[12 15 18]


In [11]:
#fancy indexing
import numpy as np
arr = np.array([10,20,4,3,90,100])
print(arr)
arr_f= arr[[0,2]]
print(arr_f)

[ 10  20   4   3  90 100]
[10  4]


In [13]:
#where
import numpy as np
arr = np.array([10,20,4,3,90,100])
print(arr)
arr_w= np.where(arr>9,'True','False')
print(arr_w)

[ 10  20   4   3  90 100]
['True' 'True' 'False' 'False' 'True' 'True']


In [19]:
arr1 = np.array([5,6,7,8,11,24,16,19,25])
print(arr1)
print(np.where((arr1>10)&(arr1<20),arr1*2,arr1+2))

[ 5  6  7  8 11 24 16 19 25]
[ 7  8  9 10 22 26 32 38 27]


In [24]:
import numpy as np
arr1= np.array([10,20,30])
arr2= np.array([1,2,3])

#Concatenate
arr_arr2 = np.concatenate((arr1,arr2))
print(arr_arr2)


[10 20 30  1  2  3]


In [23]:
#concatenate 2d
arr1= np.array([[10,20,30],[40,50,60]])
arr2= np.array([[1,2,3],[4,5,6]])
arr_arr2 = np.concatenate((arr1,arr2))
print(arr_arr2)

[[10 20 30]
 [40 50 60]
 [ 1  2  3]
 [ 4  5  6]]


In [28]:
#concatenate 2d
arr1= np.array([[10,20,30],[40,50,60]])
arr2= np.array([[1,2,3],[4,5,6]])
arr_arr2 = np.concatenate((arr1,arr2),axis=1)#col=1,raw=0 only this case
print(arr_arr2)

[[10 20 30  1  2  3]
 [40 50 60  4  5  6]]


In [26]:
import numpy as np
arr1= np.array([[[10,20,30],[40,50,60]],[[1,2,3],[4,5,6]]])
arr2= np.array([[[100,200,300],[400,500,600]],[[10,20,30],[40,50,60]]])
arr_arr2 = np.concatenate((arr1,arr2))
print(arr_arr2)

[[[ 10  20  30]
  [ 40  50  60]]

 [[  1   2   3]
  [  4   5   6]]

 [[100 200 300]
  [400 500 600]]

 [[ 10  20  30]
  [ 40  50  60]]]


In [29]:
#vstack --> vartical join | raw wise
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = np.vstack((arr1,arr2))
print(result)


[[1 2 3]
 [4 5 6]]


In [30]:
#hstack ---> horizontally join |column wise
import numpy as np
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
print(np.hstack((arr1,arr2)))


[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [32]:
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
arr3 = np.hstack((arr1,arr2))
print(arr3)


[10 20 30 40 50 60]


In [35]:
#concatenate 2d
arr1= np.array([[10,20,30],[40,50,60]])
arr2= np.array([[1,2,3],[4,5,6]])
arr_arr2 = np.hstack((arr1,arr2))
print(arr_arr2)

[[10 20 30  1  2  3]
 [40 50 60  4  5  6]]


In [33]:
#2d
import numpy as np
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
print(np.hstack((arr1,arr2)))


[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [36]:
#sum
import numpy as np
arr = np.array([10,20,30,40,50])
print(np.sum(arr))

150


In [38]:
#mean
import numpy as np
arr = np.array([10,20,30,40,50])
print(np.mean(arr))

30.0


In [39]:
#min
import numpy as np
arr = np.array([10,20,30,40,50])
print(np.min(arr))

10


In [41]:
#max
import numpy as np
arr = np.array([10,20,30,40,50])
print(np.max(arr))

50


In [43]:
#median
import numpy as np
arr = np.array([10,20,30,40,50])
print(np.median(arr))

30.0


1. p.sum(a) -> Sum of all elements
2. np.mean(a) -> Average = Sum of elements / Number of elements
3. np.median(a) -> Middle value after sorting
4. np.min(a) -> Smallest value in array
5. np.max(a) -> Largest value in array
6. np.var(a) mean,difference,square,average | (sum = ddof) -> divide by array length
7. np.std(a) -> Standard Deviation = √Variance -> Measures spread of data
8. np.prod(a) -> Multiplication of all elements
9. np.cumsum(a) -> Cumulative (running) sum
10. np.cumprod(a) -> Cumulative (running) product
12. np.argmin(a) -> Index position of minimum value
13. np.argmax(a) -> Index position of maximum value
14. np.abs(a) -> Converts negative values to positive -> Absolute value (distance from zero)
15. np.unique(a) -> Returns unique values only -> Removes duplicates
16. np.percentile(a, 50) -> Finds percentage-based value -> 50th percentile = Median
17. np.quantile(a, 0.5) -> Similar to percentile -> 0.5 = 50%
18. np.ptp(a) -> Range = Max - Min
19. np.any(a) -> True if at least one value is True





In [57]:
#var
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(np.var(arr))
#standard derivation
print(np.std(arr))
print(np.prod(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))
print(np.argmax(arr))
print(np.argmin(arr))
print(np.abs(arr))
print(np.unique(arr))
print(np.quantile(arr,0.50))
print(np.percentile(arr,50))
print(np.ptp(arr))
print(np.any(arr))


4.0
2.0
5040
[ 1  3  6 10 15 21 28]
[   1    2    6   24  120  720 5040]
6
0
[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]
4.0
4.0
6
True


# handling missing value

In [62]:
from re import L
import numpy as np
arr = np.array([10,20,np.nan,40])
print(arr)
#isnan
print(np.isnan(arr))
new_arr = np.nan_to_num(arr,nan = 100)
print(new_arr)


[10. 20. nan 40.]
[False False  True False]
[ 10.  20. 100.  40.]


In [71]:
import numpy as np

sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],
    [2, 120000, 140000, 160000, 190000],
    [3, 200000, 230000, 260000, 300000],
    [4, 180000, 210000, 240000, 270000],
    [5, 160000, 185000, 205000, 230000]
])
print(sales_data)
print(sales_data.shape)
print(sales_data.ndim)
print(sales_data.size)
print(sales_data[:,0])
print(sales_data[:,1])
print(sales_data[:,4])
print(np.max(sales_data[:,1:]))
print(np.min(sales_data[:,1:]))
print(np.sum(sales_data[:,1]))
print(np.mean(sales_data[:,4]))
print(np.sum(sales_data[:,1:],axis=1))
print(np.mean(sales_data[:,1:],axis=1))

[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]
 [     4 180000 210000 240000 270000]
 [     5 160000 185000 205000 230000]]
(5, 5)
2
25
[1 2 3 4 5]
[150000 120000 200000 180000 160000]
[250000 190000 300000 270000 230000]
300000
120000
810000
248000.0
[800000 610000 990000 900000 780000]
[200000. 152500. 247500. 225000. 195000.]


In [66]:
import numpy as np

# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

# 1. Print complete dataset
print("1. Complete Dataset:")
print(sales_data)

# 2. Shape of array
print("\n2. Shape of Array:")
print(sales_data.shape)

# 3. Number of dimensions
print("\n3. Number of Dimensions:")
print(sales_data.ndim)

# 4. Total number of elements
print("\n4. Total Number of Elements:")
print(sales_data.size)

# 5. Restaurant IDs
print("\n5. Restaurant IDs:")
print(sales_data[:, 0])

# 6. 2021 sales data
print("\n6. 2021 Sales Data:")
print(sales_data[:, 1])

# 7. 2024 sales data
print("\n7. 2024 Sales Data:")
print(sales_data[:, 4])

# 8. Maximum sales value
print("\n8. Maximum Sales Value:")
print(np.max(sales_data[:, 1:]))

# 9. Minimum sales value
print("\n9. Minimum Sales Value:")
print(np.min(sales_data[:, 1:]))

# 10. Total sales of all restaurants in 2021
print("\n10. Total Sales in 2021:")
print(np.sum(sales_data[:, 1]))

# 11. Average sales in 2024
print("\n11. Average Sales in 2024:")
print(np.mean(sales_data[:, 4]))

# 12. Total sales of each restaurant
print("\n12. Total Sales of Each Restaurant:")
print(np.sum(sales_data[:, 1:], axis=1))

# 13. Average sales of each restaurant
print("\n13. Average Sales of Each Restaurant:")
print(np.mean(sales_data[:, 1:], axis=1))

1. Complete Dataset:
[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]
 [     4 180000 210000 240000 270000]
 [     5 160000 185000 205000 230000]]

2. Shape of Array:
(5, 5)

3. Number of Dimensions:
2

4. Total Number of Elements:
25

5. Restaurant IDs:
[1 2 3 4 5]

6. 2021 Sales Data:
[150000 120000 200000 180000 160000]

7. 2024 Sales Data:
[250000 190000 300000 270000 230000]

8. Maximum Sales Value:
300000

9. Minimum Sales Value:
120000

10. Total Sales in 2021:
810000

11. Average Sales in 2024:
248000.0

12. Total Sales of Each Restaurant:
[800000 610000 990000 900000 780000]

13. Average Sales of Each Restaurant:
[200000. 152500. 247500. 225000. 195000.]
