<a href="https://colab.research.google.com/github/Ramsaini786/Aws-python/blob/main/Day9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpay Array operation

In [16]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[2])
print(arr[0:4])#slicing
print(arr[-1])
print(arr[:])
print(arr[0:3:2])# start from 0 to 3
print(arr[::2])# jump by one
print(arr[::-1])#reserve
print(arr[::-2])
print(arr[3:])

3
[1 2 3 4]
5
[1 2 3 4 5]
[1 3]
[1 3 5]
[5 4 3 2 1]
[5 3 1]
[4 5]


In [23]:
#2d
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr[0:2])#row
print(arr[:,1])#all row
print(arr[0,0])


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[2 5]
1


In [69]:
import numpy as np
arr = np.array([[10,20],[30,40]])
#print(arr)
print(arr[0,1])
print(arr[1,1])
print(arr[1,0])
print(arr[0,0])
print(arr[:,-1])
print(arr[1:,1])
print(arr[[0,1],[1,0]])
print(arr[[1,0],[0,1]])
#print(arr[1:0,0:1])



20
40
30
10
[20 40]
[40]
[20 30]
[30 20]


In [82]:
import numpy as np
arr = np.array([[2453,75,183975],
               [5795,99,573705],
               [4100,36,147600],
               [7526,86,647236],
               [9528,45,428760],
               [10788,17,183396]])
print(arr)
print(arr[[0,0,0,1],[0,1,2,1]])
print(arr[[2,3,3,3],[0,0,1,2]])
print(arr[[4,4,5,5],[1,2,1,2]])

[[  2453     75 183975]
 [  5795     99 573705]
 [  4100     36 147600]
 [  7526     86 647236]
 [  9528     45 428760]
 [ 10788     17 183396]]
[  2453     75 183975     99]
[  4100   7526     86 647236]
[    45 428760     17 183396]


In [91]:
#3d Example
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr.ndim)#3d
print("=>",arr[0])#block
print("=>>",arr[0,0])#block->row
print("=>>>",arr[0,0,0])# block-> row -> cols
print(arr[0,1,2])
print(arr[:,0]) # All block -> row ->0
print(arr[:,:,0]) # All block -> row -> cols 0

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
=> [[1 2 3]
 [4 5 6]]
=>> [1 2 3]
=>>> 1
6
[[1 2 3]
 [7 8 9]]
[[ 1  4]
 [ 7 10]]


#loop on numpy

In [103]:
#1d
import numpy as np
arr = np.array([10,20,30,40])
print(arr)
for i in arr:
  print(i)


[10 20 30 40]
10
20
30
40


In [102]:
#2d
import numpy as np
arr1 = np.array([[10,20,30],[40,50,60]])
print(arr)
for i in arr1:
  for j in i:
    print(j)



[[10 20 30]
 [40 50 60]]
10
20
30
40
50
60


In [100]:
#3d
import numpy as np
arr2 = np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])
print(arr)
for i in arr2:
  for j in i:
     for k in j:
      print(k)


[[10 20 30]
 [40 50 60]]
10
20
30
40
50
60
70
80
90
100
110
120


In [105]:
for i in np.nditer(arr2):
  print(i)
for i in arr2.flatten():
  print(i)

10
20
30
40
50
60
70
80
90
100
110
120
10
20
30
40
50
60
70
80
90
100
110
120


#sorting

In [108]:
#1d
import numpy as np
arr = np.array([10,35,40,7,15])
print(arr)
print(np.sort(arr)) #assending
print(np.sort(arr)[::-1]) #dessending


[10 35 40  7 15]
[ 7 10 15 35 40]
[40 35 15 10  7]


In [113]:
import numpy as np
arr = np.array([[10,4,50],[20,7,9]])
print(arr)
print(np.sort(arr))
print(np.sort(arr,axis=0))#colum-->0
print(np.sort(arr,axis=1))#row-->1
print(np.sort(arr)[:,::-1])

[[10  4 50]
 [20  7  9]]
[[ 4 10 50]
 [ 7  9 20]]
[[10  4  9]
 [20  7 50]]
[[ 4 10 50]
 [ 7  9 20]]
[[50 10  4]
 [20  9  7]]


#Filter

In [116]:
#filter 1d
import numpy as np
arr = np.array([10,20,30,40])
print(arr[arr>30])
print(arr[arr<30])
print(arr[arr%2==0])


[40]
[10 20]
[10 20 30 40]


In [118]:
#where
import numpy as np
arr = np.array([10,20,30,40])
print(np.where(arr>30,"true","false"))
print(np.where(arr%2==0))
print(np.where(arr>20,arr*2,arr))

['false' 'false' 'false' 'true']
(array([0, 1, 2, 3]),)
[10 20 60 80]
